# Spotify API Credentials
SPOTIPY_CLIENT_ID = "your_spotify_client_id_here"
SPOTIPY_CLIENT_SECRET = "your_spotify_client_secret_here"

# Setlist.fm API Key
SETLISTFM_API_KEY = "your_setlistfm_api_key_here"

# Optional Debug Settings
LOG_LEVEL = "INFO" 